<a href="https://colab.research.google.com/github/MariamKotob/ML2-notebook/blob/master/5_KNN_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
#Importing libs
import numpy as np
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier

In [5]:
# First Feature
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
# Second Feature
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot',
'Mild']
# Label or target varible
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No'] 

In [10]:
#In order to make caculations on String saved data we encode the labels using preprocessing from sklearn lib
le = preprocessing.LabelEncoder()
weather_encoded = le.fit_transform(weather)
print("Weather Encoded: ")
weather_encoded

Weather Encoded: 


array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [13]:
temp_encoded = le.fit_transform(temp)
print("Temperature Encoded: ")
temp_encoded

Temperature Encoded: 


array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [14]:
label_encoded = le.fit_transform(play)
print("Labels Encoded: ")
label_encoded

Labels Encoded: 


array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [15]:
features = list(zip(weather_encoded, temp_encoded))

In [19]:
#Calling the trained model giving the current data| our model will calculate values based on the 3 closest values
model = KNeighborsClassifier(n_neighbors=3)

#Send trining data to the model to start training
model.fit(features, label_encoded)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [21]:
#Now we make sample testing data to provid to the model in order to test the performance 
test = np.array([0, 2])
test_reshaped = test.reshape(1, 2)
prediction = model.predict(test_reshaped) 
prediction

array([1])